// Think Mink NYC — data layer

const TM_DATA = {
  // === Wigs ===
  wigs: [
    {
      id: "wig-1",
      name: "Natural Black 1B Full Lace — Body Wave",
      tags: ["full-lace"],
      price: 425,
      length: '18"–24"',
      meta: "Full lace · body wave · 1B",
      grad: ["#1a1a1a", "#3a2230"],
    },
    {
      id: "wig-2",
      name: "Natural Black 1B Frontal — Body Wave",
      tags: ["frontal"],
      price: 320,
      length: '18"–22"',
      meta: "13x4 frontal · body wave · 1B",
      grad: ["#0f0f0f", "#3d2c4a"],
    },
    {
      id: "wig-3",
      name: "Natural Black 1B Frontal — Water Wave",
      tags: ["frontal"],
      price: 340,
      length: '18"–24"',
      meta: "13x4 frontal · water wave · 1B",
      grad: ["#1c1c1c", "#244658"],
    },
    {
      id: "wig-4",
      name: "613 Blonde Frontal — Mink Straight",
      tags: ["frontal", "blonde"],
      price: 380,
      length: '20"–28"',
      meta: "13x4 frontal · straight · 613",
      grad: ["#cda77a", "#f0d39b"],
      darkText: true,
    },
    {
      id: "wig-5",
      name: "613 Blonde Frontal — Body Wave",
      tags: ["frontal", "blonde"],
      price: 380,
      length: '20"–28"',
      meta: "13x4 frontal · body wave · 613",
      grad: ["#d1ab83", "#f4dbab"],
      darkText: true,
    },
    {
      id: "wig-6",
      name: "613 Blonde Bob",
      tags: ["bob", "blonde"],
      price: 260,
      length: '10"–14"',
      meta: "Bob silhouette · 613 · cut and styled",
      grad: ["#c79a6c", "#ecc78a"],
      darkText: true,
    },
    {
      id: "wig-7",
      name: "1B Natural Bob",
      tags: ["bob"],
      price: 240,
      length: '10"–14"',
      meta: "Bob silhouette · 1B · sleek finish",
      grad: ["#101010", "#2c2a2c"],
    },
    {
      id: "wig-8",
      name: "Red Bob — Straight or Body",
      tags: ["bob"],
      price: 280,
      length: '10"–14"',
      meta: "Statement red · custom texture",
      grad: ["#7a0e1a", "#d2253b"],
    },
  ],

  // === Frontals & Closures ===
  frontals: [
    {
      id: "fc-1",
      name: "Mink Straight Closure",
      tags: ["closure"],
      price: 110,
      meta: "4x4 HD lace · 1B",
      grad: ["#0d0d0d", "#332b3b"],
    },
    {
      id: "fc-2",
      name: "Mink Curly Closure",
      tags: ["closure"],
      price: 120,
      meta: "4x4 HD lace · curly · 1B",
      grad: ["#1a1418", "#3c2535"],
    },
    {
      id: "fc-3",
      name: "Mink Body Closure",
      tags: ["closure"],
      price: 120,
      meta: "4x4 HD lace · body wave · 1B",
      grad: ["#0f0f0f", "#3d2c4a"],
    },
    {
      id: "fc-4",
      name: "Mink Straight Frontal",
      tags: ["frontal"],
      price: 165,
      meta: "13x4 HD lace · straight · 1B",
      grad: ["#0d0d0d", "#3a2735"],
    },
    {
      id: "fc-5",
      name: "Mink Body Wave Frontal",
      tags: ["frontal"],
      price: 175,
      meta: "13x4 HD lace · body wave · 1B",
      grad: ["#101010", "#3e2b48"],
    },
    {
      id: "fc-6",
      name: "613 Body Wave Frontal",
      tags: ["frontal", "blonde"],
      price: 195,
      meta: "13x4 HD lace · body wave · 613",
      grad: ["#d1ab83", "#f4dbab"],
      darkText: true,
    },
    {
      id: "fc-7",
      name: "613 Body Wave Closure",
      tags: ["closure", "blonde"],
      price: 145,
      meta: "4x4 HD lace · body wave · 613",
      grad: ["#cca37c", "#eeca8a"],
      darkText: true,
    },
    {
      id: "fc-8",
      name: "613 Mink Straight Frontal",
      tags: ["frontal", "blonde"],
      price: 195,
      meta: "13x4 HD lace · straight · 613",
      grad: ["#c99a6c", "#ebc789"],
      darkText: true,
    },
    {
      id: "fc-9",
      name: "613 Blonde Straight Closure",
      tags: ["closure", "blonde"],
      price: 145,
      meta: "4x4 HD lace · straight · 613",
      grad: ["#caa37b", "#edc78a"],
      darkText: true,
    },
  ],

  // === Bundles ===
  bundles: [
    {
      id: "b-straight",
      name: "Mink Straight Bundle",
      tags: ["straight"],
      price: 110,
      meta: 'Sold by length, 18"–32"',
      grad: ["#0c0c0c", "#3a2735"],
    },
    {
      id: "b-body",
      name: "Mink Body Wave Bundle",
      tags: ["body"],
      price: 115,
      meta: 'Sold by length, 18"–32"',
      grad: ["#0d0d0d", "#3c2a48"],
    },
    {
      id: "b-curly",
      name: "Mink Curly Bundle",
      tags: ["curly"],
      price: 120,
      meta: 'Sold by length, 18"–28"',
      grad: ["#1a1318", "#3f2438"],
    },
    {
      id: "b-water",
      name: "Mink Water Wave Bundle",
      tags: ["water"],
      price: 120,
      meta: 'Sold by length, 18"–28"',
      grad: ["#0e0e0e", "#234a5c"],
    },
    {
      id: "b-deep",
      name: "Mink Deep Wave Bundle",
      tags: ["body"],
      price: 125,
      meta: 'Sold by length, 18"–32"',
      grad: ["#10101a", "#1c2a52"],
    },
    {
      id: "b-613-straight",
      name: "613 Blonde Straight Bundle",
      tags: ["straight"],
      price: 145,
      meta: 'Sold by length, 18"–28"',
      grad: ["#c99c6e", "#edc88a"],
      darkText: true,
    },
    {
      id: "b-613-body",
      name: "613 Blonde Body Wave Bundle",
      tags: ["body"],
      price: 150,
      meta: 'Sold by length, 18"–28"',
      grad: ["#cba27a", "#f0cd8e"],
      darkText: true,
    },
    {
      id: "b-natural-curly",
      name: "Mink Kinky Curly Bundle",
      tags: ["curly"],
      price: 130,
      meta: '4C natural texture · 14"–22"',
      grad: ["#1a1318", "#3f2438"],
    },
  ],

  // === Stylists ===
  stylists: [
    {
      id: "jenell",
      name: "JENELL",
      role: "Founder · Master Stylist",
      bio: "The mind behind Mink. Jenell has built every chair in the studio and trained every stylist who sits in one. Specializes in melts that disappear and installs that last.",
      specialties: ["Frontal Sew-In", "Glueless Install", "Bridal"],
      grad: ["#ed45a0", "#664398"],
    },
    {
      id: "mimi",
      name: "MIMI",
      role: "Senior Stylist",
      bio: "Color theory nerd and the studio's go-to for blonde transformations. If you want a 613 install you'll never have to touch up, this is your chair.",
      specialties: ["Color", "613 Installs", "Custom Coloring"],
      grad: ["#7fccf7", "#ed45a0"],
    },
    {
      id: "lex",
      name: "LEX",
      role: "Stylist · Protective Styles",
      bio: "Braids, faux locs, knotless — Lex builds long-lasting protective styles with a scalp-first approach. Comfort, longevity, and clean partings every time.",
      specialties: ["Braids", "Faux Locs", "Knotless"],
      grad: ["#664398", "#7fccf7"],
    },
    {
      id: "chassidy",
      name: "CHASSIDY AUTUMN",
      role: "Stylist · Cuts & Color",
      bio: "Precision cuts, layers that move, and color that looks expensive. Chassidy is the chair to book when you want a finish that photographs.",
      specialties: ["Cuts", "Layers", "Highlights"],
      grad: ["#ff8dc8", "#664398"],
    },
    {
      id: "hollywood",
      name: "HOLLYWOOD",
      role: "Stylist · Quick Styles",
      bio: "Swoop ponytails, slick backs, and event-day blowouts. Need to look unreal in 90 minutes? Book Hollywood.",
      specialties: ["Pony", "Blow Out", "Event Styling"],
      grad: ["#2c2530", "#ed45a0"],
    },
  ],

  // === Lash / Beauty talent ===
  lashTeam: [
    {
      id: "lash-1",
      name: "SENIOR LASH ARTIST",
      role: "Lash · Brows",
      bio: "Volume, hybrid and classic sets — built to last 4–6 weeks. Our senior artist also handles brow shaping and tints.",
      specialties: ["Volume", "Hybrid", "Classic", "Brows"],
      grad: ["#ed45a0", "#7fccf7"],
    },
    {
      id: "lash-2",
      name: "LEAD MUA",
      role: "Makeup · Glam",
      bio: "Beats for everyday, weddings, photoshoots and red-carpet looks. Specializes in 'no makeup' makeup and detailed glitter glam.",
      specialties: ["Soft Glam", "Bridal", "Glitter Glam"],
      grad: ["#7fccf7", "#664398"],
    },
    {
      id: "lash-3",
      name: "NAIL ARTIST",
      role: "Nails · Glass",
      bio: "Clear glass nails, structured gels and chrome finishes. Sets last and grow out clean.",
      specialties: ["Glass Nails", "Gel-X", "Chrome"],
      grad: ["#ff8dc8", "#ed45a0"],
    },
  ],

  // === Services (used for booking) ===
  services: [
    {
      id: "wig-glueless",
      cat: "Hair",
      name: "Wig Install — Glueless",
      duration: 90,
      price: 150,
      desc: "Lay, custom-cut, and style — no glue.",
    },
    {
      id: "wig-glued",
      cat: "Hair",
      name: "Wig Install — Glued",
      duration: 120,
      price: 220,
      desc: "Full melt, glued lace, styled to finish.",
    },
    {
      id: "frontal-sewin",
      cat: "Hair",
      name: "Frontal Sew-In Install",
      duration: 180,
      price: 250,
      desc: "Braid down, sew-in, frontal lay and style.",
    },
    {
      id: "wash-set",
      cat: "Hair",
      name: "Wash & Set",
      duration: 60,
      price: 65,
      desc: "Cleanse, condition, blow-dry, set.",
    },
    {
      id: "cut",
      cat: "Hair",
      name: "Cut & Shape",
      duration: 45,
      price: 50,
      desc: "Custom cut on natural hair or wig.",
    },
    {
      id: "braids-pony",
      cat: "Hair",
      name: "Braids to Ponytail",
      duration: 90,
      price: 90,
      desc: "Sleek braided pony — feed-ins available.",
    },
    {
      id: "swoop-pony",
      cat: "Hair",
      name: "Swoop Pony / Slick Back",
      duration: 60,
      price: 75,
      desc: "Glassy slick + sculpted swoop edge.",
    },
    {
      id: "faux-locs",
      cat: "Hair",
      name: "Faux Locs",
      duration: 240,
      price: 250,
      desc: "Soft locs, full install — multi-length options.",
    },
    {
      id: "frontal-class",
      cat: "Education",
      name: "One-on-One Frontal Class",
      duration: 240,
      price: 625,
      desc: "Private 4-hour class with materials.",
    },
    {
      id: "lash-full",
      cat: "Lash",
      name: "Lash Full Set",
      duration: 90,
      price: 200,
      desc: "Classic, hybrid, or volume — your choice.",
    },
    {
      id: "lash-fill",
      cat: "Lash",
      name: "Lash Fill",
      duration: 60,
      price: 95,
      desc: "Top-up within 3 weeks of your last set.",
    },
    {
      id: "lash-removal",
      cat: "Lash",
      name: "Lash Removal",
      duration: 30,
      price: 50,
      desc: "Safe removal of any lash set.",
    },
    {
      id: "beat-classic",
      cat: "Beauty",
      name: "Classic Soft Beat",
      duration: 45,
      price: 80,
      desc: "Natural soft beat with neutral eye.",
    },
    {
      id: "beat-glam",
      cat: "Beauty",
      name: "Soft Glam Beat",
      duration: 60,
      price: 120,
      desc: "Everyday glam with cut crease + lash.",
    },
    {
      id: "beat-glitter",
      cat: "Beauty",
      name: "Glitter Glam Beat",
      duration: 75,
      price: 150,
      desc: "Detailed glitter eye, bold beat, lashes.",
    },
    {
      id: "nails-glass",
      cat: "Beauty",
      name: "Clear Glass Nails",
      duration: 75,
      price: 90,
      desc: "Glass-clear set, structured shape.",
    },
  ],

  // === Featured products to highlight on home ===
  get featuredIds() {
    return ["wig-4", "wig-1", "fc-5", "wig-8", "b-curly", "wig-6"];
  },

  // === Helper lookups ===
  serviceById(id) {
    return this.services.find((s) => s.id === id);
  },
  stylistById(id) {
    return this.stylists.find((s) => s.id === id);
  },
  allStaff() {
    return [...this.stylists, ...this.lashTeam];
  },
};

window.TM_DATA = TM_DATA;
